version: "3.1"
services:
  solr:
    build: edition-archive-backend/edition-archive-backend-webapp/src/main/solr
    ports:
      - ${SOLR_HTTP}:8983
    restart: always
    volumes:
      - ${SOLR_DATA}:/var/solr/data
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: eab
    volumes:
      - ${DB_DATA}:/var/lib/postgresql/data/
    ports:
      - ${DB_PORT}:5432
  backend:
    build: edition-archive-backend
    environment:
      TOMCAT_PASSWORD: test
      JDBC_NAME: ${DB_USER}
      JDBC_PASSWORD: ${DB_PASSWORD}
      JDBC_DRIVER: org.postgresql.Driver
      JDBC_URL: jdbc:postgresql://db:5432/eab
      SOLR_URL: http://solr:8983
      SOLR_CLASSIFICATION_CORE: classification
      SOLR_CORE: main
      XMX: 1G
      XMS: 1G
    volumes:
      - ${BACKEND_HOME}:/mcr/home/
      - ${BACKEND_DATA}:/mcr/data/
      - ${BACKEND_TMP}:/mcr/tmp/
      - ${BACKEND_LOG}:/mcr/logs/
    depends_on:
      - db
      - solr
    ports:
      - ${BACKEND_HTTP}:8080
      - ${BACKEND_AJP}:8009
  frontend:
    build: edition-archive-frontend
    user: node
    environment:
      - NODE_ENV=production
    ports:
      - ${FRONTEND_PORT}:3000
  apache:
    image: httpd:2.4
    ports:
      - 8000:80
      - 4430:443
    volumes:
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - backend
      - frontend
      - solr


